(function () {
	if (typeof _ === 'undefined' || typeof lang === 'undefined' || lang !== 'zh_cn') {
		return;
	}

	_.setTranslation({
		"A Dark Room": "深空苏醒",
		"Room": "核心舱",
		"A Firelit Room": "已点亮的核心舱",
		"light fire": "启动反应炉",
		"stoke fire": "烧锅炉",
		"the room is {0}": "核心舱{0}",
		"the fire is {0}": "反应炉{0}",
		"builder stokes the fire": "工程师给反应堆补充燃料",
		"not enough wood to get the fire going": "废金属不足，无法启动反应堆",
		"the wood has run out": "废金属已耗尽",
		"the wood is running out": "废金属即将耗尽",
		"the light from the fire spills from the windows, out into the dark": "反应堆的冷光透出舷窗，照进黑暗",
		"Outside": "舱外荒域",
		"A Silent Forest": "寂静星野",
		"A Dusty Path": "尘封航道",
		"forest": "星野",
		"village": "前哨殖民站",
		"A Lonely Hut": "孤立居住舱",
		"A Tiny Village": "微型殖民站",
		"A Modest Village": "标准殖民站",
		"A Large Village": "大型殖民站",
		"A Raucous Village": "繁忙殖民枢纽",

		"stores": "仓储舱",
		"build:": "建造:",
		"craft:": "制造:",

		"wood": "废金属",
		"fur": "隔热材料",
		"scraps of fur": "隔热材料碎片",
		"meat": "合成补给",
		"bits of meat": "合成补给包",
		"teeth": "合金齿片",
		"scattered teeth": "零散合金齿片",
		"leather": "聚合皮层",
		"iron": "铁锭",
		"steel": "钛钢",
		"coal": "碳素燃料",
		"sulphur": "硫晶",
		"scales": "护甲鳞片",
		"strange scales": "异星护甲鳞片",
		"cloth": "纳米布",
		"tattered cloth": "破损纳米布",
		"bullets": "动能弹",
		"torch": "照明棒",
		"medicine": "医疗针剂",
		"charm": "量子护符",
		"bait": "诱饵模块",
		"cured meat": "压缩口粮",
		"energy cell": "能量电芯",
		"water": "氧气",
		"water replenished": "氧气已补满",
		"there is no more water": "氧气已耗尽",
		"the thirst becomes unbearable": "缺氧变得难以忍受",
		"waterskin": "便携氧气瓶",
		"this waterskin'll hold a bit of water, at least": "这个便携氧气瓶至少能装一点氧气",
		"cask": "氧气罐",
		"the cask holds enough water for longer expeditions": "氧气罐可为更长途的探索提供氧气",
		"water tank": "高压氧气舱",
		"never go thirsty again": "再也不用担心缺氧",
		"eat meat": "使用合成补给",
		"not enough fur": "隔热材料不足",
		"not enough wood": "废金属不足",
		"not enough meat": "合成补给不足",
		"the meat has run out": "合成补给已耗尽",
		"go twice as far without eating": "在不补给的情况下，航程翻倍",
		"go twice as far without drinking": "在不补氧的情况下，航程翻倍",
		"a stranger arrives in the night": "夜间，一名陌生幸存者抵达舱门外",
		"a weathered family takes up in one of the huts.": "一支饱经风暴的流亡家庭入住了居住舱",
		"a small group arrives, all dust and bones.": "一小队风尘仆仆的流亡者抵达前哨",
		"a convoy lurches in, equal parts worry and hope.": "一支运输车队摇晃驶入，载着同等分量的不安与希望",
		"the town's booming. word does get around.": "殖民站进入扩张期，航道上的消息传得很快",
		"the sky is grey and the wind blows relentlessly": "天幕灰暗，辐尘风持续横扫荒域",
		"dry brush and dead branches litter the forest floor": "星野地表遍布枯化植株与断裂纤维枝",
		"the traps contain ": "回收网捕获了",
		"the compass points ": "导航阵列指向:",
		"dangerous to be this far from the village without proper protection": "缺少防护就离前哨这么远，风险极高",
		"safer here": "此处信号稳定，风险较低",
		"starvation sets in": "能量赤字开始侵蚀生理系统",
		"the trees yield to dry grass. the yellowed brush rustles in the wind.": "高大植群退化成干草带，发黄灌丛在风中摩擦作响",
		"the trees are gone. parched earth and blowing dust are poor replacements.": "树冠层已经消失，只剩龟裂地表与卷动尘流",
		"trees loom on the horizon. grasses gradually yield to a forest floor of dry branches and fallen leaves.": "地平线上浮现稀疏林线，草地逐渐让位给堆满枯枝落叶的林底",
		"the grasses thin. soon, only dust remains.": "草带迅速变薄，很快只剩扬尘",
		"the barrens break at a sea of dying grass, swaying in the arid breeze.": "荒地在一片濒死草海处断开，干热气流推动草浪起伏",
		"a wall of gnarled trees rises from the dust. their branches twist into a skeletal canopy overhead.": "扭曲树墙从尘雾中隆起，枝桠在头顶交织成骨架般穹顶",
		"the world fades": "视野信号衰减，世界开始淡出",
		"a nomad arrives, looking to trade": "一支游商队抵达，请求进行物资交换",
		"through the walls, shuffling noises can be heard.": "舱壁后传来拖行与摩擦声",
		"can't tell what they're up to.": "暂时无法判定其意图",
		"strange noises can be heard through the walls": "舱壁另一侧传来异常噪声",
		"vague shapes move, just out of sight.": "模糊身影在监控边缘掠过",
		"the sounds stop.": "异常声源中断",
		"the night is silent.": "夜间频道恢复静默",
		"scratching noises can be heard from the store room.": "仓储舱传来抓刮与摩擦声",
		"something's in there.": "里面有未知目标",
		"something's in the store room": "未知目标已入侵仓储舱",
		"some wood is missing.": "部分废金属库存缺失",
		"a thief is caught": "已捕获一名入侵窃贼",
		"some traps have been destroyed": "部分回收网被外力损毁",
		"a fire has started": "舱区发生火情",
		"some villagers have died": "有殖民者在事故中遇难",
		"a sickness is spreading through the village.": "感染症正在殖民站内扩散",
		"medicine is needed immediately.": "需要立即投入医疗针剂",
		"some villagers are ill": "部分殖民者出现感染症状",
		"the sickness spreads through the village.": "感染在殖民站继续扩散",
		"a plague afflicts the village": "高危疫病席卷殖民站",
		"A Beast Attack": "异星生物突袭",
		"a pack of snarling beasts pours out of the trees.": "一群嘶吼的异星生物从星野掩体后突然涌出",
		"the fight is short and bloody, but the beasts are repelled.": "交火短促而惨烈，但防线最终将其击退",
		"the villagers retreat to mourn the dead.": "殖民者后撤清点伤亡，并为阵亡者默哀",
		"wild beasts attack the villagers": "异星生物群正在冲击前哨殖民站",
		"predators become prey. price is unfair": "猎手与猎物的身份在瞬间互换，代价沉重",
		"A Military Raid": "武装突袭警报",
		"a gunshot rings through the trees.": "一声枪响划破星野静默",
		"well armed men charge out of the forest, firing into the crowd.": "重装武装人员从掩体后突进，向人群持续开火",
		"after a skirmish they are driven away, but not without losses.": "短暂交战后敌方被迫撤离，但我们付出了伤亡代价",
		"troops storm the village": "敌方部队正在突入前哨殖民站",
		"warfare is bloodthirsty": "战场只讲生存，不讲仁慈",
		"troops storm the village": "武装部队突入殖民站",
		"a shot rings out, from somewhere in the long grass": "长草带深处传来一声枪响",
		"a soldier opens fire from across the desert": "一名士兵在荒漠另一端开火",
		"the villagers haul a filthy man out of the store room.": "殖民者把一名肮脏可疑人员从仓储舱拖了出来",
		"say his folk have been skimming the supplies.": "据称其同伙长期在转运物资",
		"say he should be strung up as an example.": "有人主张公开处置以示警戒",
		"the point is made. in the next few days, the missing supplies are returned.": "震慑起效，几天后失踪物资陆续回流",
		"the mouth of the cave is wide and dark.": "洞口宽阔而深暗，像一道未关闭的地层裂隙",
		"can't see what's inside.": "探照范围内无法解析内部结构",
		"the earth here is split, as if bearing an ancient wound": "地层在此撕裂，像远古撞击留下的伤口",
		"a startled beast defends its home": "受惊生物开始防御性反击",
		"the cave narrows a few feet in.": "前方通道迅速收束",
		"the walls are moist and moss-covered": "岩壁潮湿，附着大面积生物膜",
		"the remains of an old camp sits just inside the cave.": "洞内留有一处早年临时营地残迹",
		"bedrolls, torn and blackened, lay beneath a thin layer of dust.": "破损发黑的睡袋被薄尘覆盖",
		"the body of a wanderer lies in a small cavern.": "一名流浪者的遗体躺在狭小空腔中",
		"rot's been to work on it, and some of the pieces are missing.": "腐败过程已持续很久，部分组织缺失",
		"the torch sputters and dies in the damp air": "照明棒在潮湿空气中闪烁后熄灭",
		"the darkness is absolute": "黑暗完全吞没视野",
		"a cave lizard attacks": "洞穴爬行体发起突袭",
		"a large beast charges out of the dark": "大型生物从黑暗深处高速冲出",
		"a giant lizard shambles forward": "巨型爬行体拖着沉重步伐逼近",
		"the town lies abandoned, its citizens long dead": "这座聚居点已被废弃，原住民早已消失",
		"broken streetlights stand, rusting. light hasn't graced this place in a long time.": "折断的路灯在锈蚀中伫立，这里很久没再迎来照明",
		"a scavenger waits just inside the door.": "门后潜伏着一名拾荒者",
		"a madman attacks, screeching.": "一名精神失序者尖叫着扑来",
		"a thug moves out of the shadows.": "一名暴徒从阴影中现身",
		"a beast charges out of a ransacked classroom.": "一头生物从被洗劫的教室猛冲而出",
		"the towers of a decaying city dominate the skyline": "衰败城市的高塔仍主宰着天际线",
		"the streets are empty.": "街道空旷，回声清晰可辨",
		"the air is filled with dust, driven relentlessly by the hard winds.": "强风裹挟尘埃持续横扫城市峡谷",
		"the shell of an abandoned hospital looms ahead.": "一座废弃医院的骨架矗立在前方",
		"a huge lizard scrambles up out of the darkness of an old metro station.": "一只巨型爬行体从旧地铁站的黑暗里爬出",
		"the shot echoes in the empty street.": "枪声在空街与楼体间反复回荡",
		"the soldier steps out from between the buildings, rifle raised.": "士兵从楼体缝隙走出，步枪已抬起",
		"a frail man stands defiantly, blocking the path.": "一名瘦弱男子固执地挡在通道中央",
		"the tunnel opens up at another platform.": "隧道在前方扩展到另一处站台",
		"the walls are scorched from an old battle.": "墙体仍残留旧战火灼烧痕迹",
		"bodies and supplies from both sides litter the ground.": "双方遗骸与散落物资覆盖地面",
		"the small military outpost is well supplied.": "这处小型军用哨点物资充足",
		"the military is already set up at the mine's entrance.": "武装单位已在矿井入口建立防线",
		"soldiers patrol the perimeter, rifles slung over their shoulders.": "士兵背着步枪沿周界巡逻",
		"a military perimeter is set up around the mine.": "矿区外围已部署军事封锁圈",
		"the military presence has been cleared.": "矿区内军事威胁已清除",
		"the mine is now safe for workers.": "该矿区现可恢复采掘作业",
		"camp fires burn by the entrance to the mine.": "矿井入口旁仍燃着营火",
		"this old mine is not abandoned": "这座旧矿并未真正废弃",
		"the camp is still, save for the crackling of the fires.": "营地归于寂静，只剩火焰爆裂声",
		"an old iron mine sits here, tools abandoned and left to rust.": "一座老旧铁矿静置于此，工具已锈蚀报废",
		"bleached bones are strewn about the entrance. many, deeply scored with jagged grooves.": "矿口散落着大片白化骨骸，表面布满锯齿状深痕",
		"feral howls echo out of the darkness.": "非理性咆哮从黑暗矿道深处回荡",
		"the path leads to an abandoned mine": "航迹指向一处被遗弃的矿井",
		"a large creature lunges, muscles rippling in the torchlight": "大型生物猛扑而来，肌束在照明下起伏",
		"the beast is dead.": "目标生物已失去生命体征",
		"a destroyed village lies in the dust.": "尘土中横陈着被彻底摧毁的聚居点",
		"charred bodies litter the ground.": "焦黑遗体散落满地",
		"the metallic tang of wanderer afterburner hangs in the air.": "空气里弥漫着流浪者推进器尾焰的金属气味",
		"there are still supplies inside.": "内部仍有可回收补给",
		"asks for any spare furs to keep him warm at night.": "他请求分一些多余的隔热材料，用来熬过夜间低温",
		"a wanderer arrives with an empty cart. says if she leaves with furs, she'll be back with more.": "一名流浪者推着空车抵达。她说若带走隔热材料，会再带更多物资回来",
		"the wanderer leaves, cart loaded with furs": "流浪者带着满载隔热材料的运输车离开了",
		"the mysterious wanderer returns, cart piled high with furs.": "神秘流浪者回来了，运输车上堆满了隔热材料",

		"builder": "工程师",
		"hunter": "侦猎员",
		"trapper": "捕获员",
		"tanner": "材料员",
		"charcutier": "补给员",
		"iron miner": "铁矿技师",
		"coal miner": "燃料技师",
		"sulphur miner": "硫晶技师",
		"steelworker": "合金技师",
		"armourer": "军械技师",
		"gatherer": "采集员",

		"trap": "感应陷阱",
		"gather wood": "回收废金属",
		"cart": "运输车",
		"hut": "居住舱",
		"lodge": "侦猎站",
		"trading post": "轨道交易站",
		"tannery": "材料精炼间",
		"smokehouse": "补给处理舱",
		"workshop": "工程工坊",
		"steelworks": "合金锻造厂",
		"armoury": "军械库"
	});
})();
